name: CI Pipeline

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (for multi-platform builds, optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Login to GitHub Container Registry (Optional: only if pushing images)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: docker build -t my-flask-app .

      # Step 5: Test the Docker image (Placeholder for actual tests)
      - name: Test Docker image
        run: echo "Test"

      # Step 6: Push Docker image to GitHub Container Registry (only on main branch)
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/my-flask-app:latest
        if: github.ref == 'refs/heads/main'

      # Step 7: Security scan with Trivy
      - name: Security Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: my-flask-app:latest

      # Step 8: Save Trivy report as an artifact
      - name: Save Trivy Report
        run: trivy image --format table --output trivy-report.txt my-flask-app:latest

      # Step 9: Upload Trivy report for review (optional)
      - name: Upload Trivy Report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.txt
